using Microsoft.AspNetCore.Mvc;
using TaskApp.Domain;

namespace TaskApp.Api.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class UsersController : ControllerBase
    {
        // TODO: Inject database context or user service here
        // private readonly IUserService _userService;
        // 
        // public UsersController(IUserService userService)
        // {
        //     _userService = userService;
        // }

        /// <summary>
        /// Get all users
        /// </summary>
        [HttpGet]
        public ActionResult<IEnumerable<User>> GetAll()
        {
            try
            {
                // TODO: Replace with actual database query
                // var users = await _userService.GetAllUsersAsync();
                return Ok(new List<User>());
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { message = "An error occurred while retrieving users.", error = ex.Message });
            }
        }

        /// <summary>
        /// Get user by ID
        /// </summary>
        [HttpGet("{id}")]
        public ActionResult<User> GetById(int id)
        {
            try
            {
                if (id <= 0)
                {
                    return BadRequest(new { message = "Invalid user ID." });
                }

                // TODO: Replace with actual database query
                // var user = await _userService.GetUserByIdAsync(id);
                // if (user == null)
                // {
                //     return NotFound(new { message = "User not found." });
                // }

                return Ok(new User { Id = id });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { message = "An error occurred while retrieving the user.", error = ex.Message });
            }
        }

        /// <summary>
        /// Create a new user
        /// </summary>
        [HttpPost]
        public ActionResult<User> Create([FromBody] CreateUserRequest request)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }

                if (string.IsNullOrWhiteSpace(request.Name) || string.IsNullOrWhiteSpace(request.Email))
                {
                    return BadRequest(new { message = "Name and Email are required." });
                }

                // TODO: Replace with actual database save
                // var newUser = await _userService.CreateUserAsync(request.Name, request.Email, request.Password);

                var newUser = new User
                {
                    Id = 1, // TODO: This should be generated by database
                    Name = request.Name,
                    Email = request.Email,
                    Password = request.Password
                };

                return CreatedAtAction(nameof(GetById), new { id = newUser.Id }, newUser);
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { message = "An error occurred while creating the user.", error = ex.Message });
            }
        }

        /// <summary>
        /// Update an existing user
        /// </summary>
        [HttpPut("{id}")]
        public ActionResult<User> Update(int id, [FromBody] UpdateUserRequest request)
        {
            try
            {
                if (id <= 0)
                {
                    return BadRequest(new { message = "Invalid user ID." });
                }

                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }

                // TODO: Replace with actual database update
                // var updatedUser = await _userService.UpdateUserAsync(id, request.Name, request.Email, request.Password);
                // if (updatedUser == null)
                // {
                //     return NotFound(new { message = "User not found." });
                // }

                var updatedUser = new User
                {
                    Id = id,
                    Name = request.Name,
                    Email = request.Email,
                    Password = request.Password
                };

                return Ok(updatedUser);
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { message = "An error occurred while updating the user.", error = ex.Message });
            }
        }

        /// <summary>
        /// Delete a user
        /// </summary>
        [HttpDelete("{id}")]
        public ActionResult Delete(int id)
        {
            try
            {
                if (id <= 0)
                {
                    return BadRequest(new { message = "Invalid user ID." });
                }

                // TODO: Replace with actual database delete
                // var success = await _userService.DeleteUserAsync(id);
                // if (!success)
                // {
                //     return NotFound(new { message = "User not found." });
                // }

                return NoContent();
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { message = "An error occurred while deleting the user.", error = ex.Message });
            }
        }
    }

    /// <summary>
    /// Request model for creating a user
    /// </summary>
    public class CreateUserRequest
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }

    /// <summary>
    /// Request model for updating a user
    /// </summary>
    public class UpdateUserRequest
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}
